GOOGLE:
  OAuthVersion: 2.0
  AuthURL:      https://accounts.google.com/o/oauth2/auth
  TokenURL:     https://accounts.google.com/o/oauth2/token
  UserInfoURL:  https://www.googleapis.com/oauth2/v2/userinfo
  Scopes:
    - https://www.googleapis.com/auth/userinfo.profile
    - https://www.googleapis.com/auth/userinfo.email

FACEBOOK:
  OAuthVersion: 2.0
  AuthURL:      https://www.facebook.com/dialog/oauth
  TokenURL:     https://graph.facebook.com/oauth/access_token
  UserInfoURL:  https://graph.facebook.com/me?fields=id,first_name,middle_name,last_name,email,picture
  Scopes:
    - email
    - public_profile

TWITTER:
  OAuthVersion:     1.0
  AuthURL:          https://api.twitter.com/oauth/authorize
  TokenURL:         https://api.twitter.com/oauth/access_token
  UserInfoURL:      https://api.twitter.com/1.1/account/verify_credentials.json
  RequestTokenURL:  https://api.twitter.com/oauth/request_token
